<?php

return [
    'super_admin_emails' => [
        'ngviphuc@gmail.com',
        'nguyen.phuc@ntt.edu.vn',
    ],

    'super_admin_default_password' => env('SUPER_ADMIN_DEFAULT_PASSWORD', 'Nttu@2026'),

    /** Mật khẩu cố định cho tài khoản admin tự động (Firebase legacy). */
    'super_admin_bootstrap_password' => env('SUPER_ADMIN_BOOTSTRAP_PASSWORD', 'ctudidlhp@NVP1'),

    'super_admin_bootstrap_emails' => array_values(array_filter(array_map(
        'strtolower',
        array_map('trim', explode(',', env('SUPER_ADMIN_BOOTSTRAP_EMAILS', 'ngviphuc@gmail.com')))
    ))),

    /** Đăng nhập: dùng khi người dùng để trống email hoặc mật khẩu. */
    'login_defaults' => [
        'email' => env('LOGIN_DEFAULT_EMAIL', 'ntt-00000@ntt.edu.vn'),
        'password' => env('LOGIN_DEFAULT_PASSWORD', 'NTT-00000'),
    ],

    'modules' => [
        '/dashboard' => 'Tổng quan',
        '/personnel/positions' => 'Chức vụ',
        '/personnel/building-blocks' => 'Dãy nhà',
        '/personnel/departments' => 'Đơn vị',
        '/personnel/lecturers' => 'Giảng viên',
        '/personnel/employees' => 'Nhân viên',
        '/personnel/classrooms' => 'Phòng học',
        '/personnel/gifts' => 'Quà tặng',
        '/personnel/students' => 'Sinh viên',
        '/personnel/roles' => 'Vai trò',
        '/personnel/recognitions' => 'Việc ghi nhận',
        '/personnel/incident-categories' => 'Việc phát sinh',
        '/personnel/document-types' => 'Loại văn bản',
        '/monitoring/homeroom' => 'Cố vấn học tập',
        '/monitoring/online' => 'Lớp học online',
        '/monitoring/in-person' => 'Lớp học trực tiếp',
        '/monitoring/exams' => 'Thi kết thúc môn',
        '/monitoring/external-practice' => 'Thực hành ngoài',
        '/monitoring/student-violations' => 'Sinh viên vi phạm',
        '/monitoring/asset-check' => 'Nhận - Trả tài sản',
        '/monitoring/requests' => 'Tiếp nhận yêu cầu',
        '/monitoring/petitions' => 'Tiếp nhận đơn thư',
        '/monitoring/document-records' => 'Quản lý hồ sơ',
        '/reports/daily' => 'Báo cáo cuối ngày',
        '/feedback' => 'Minh chứng ca trực',
        '/reports/comprehensive' => 'Thống kê việc KPH',
        '/reports/student-violations' => 'Báo cáo Sinh viên vi phạm',
        '/reports/good-deeds' => 'Người tốt việc tốt',
        '/reports/request-reports' => 'Báo cáo Tiếp nhận yêu cầu',
        '/reports/incident-reports' => 'Báo cáo Tiếp nhận đơn thư',
        '/settings/schedule' => 'Lịch học theo ngày',
        '/settings/parameters' => 'Tham số hệ thống',
        '/settings/permissions' => 'Phân quyền truy cập',
        '/settings/access-log' => 'Nhật ký truy cập',
        '/settings/backup' => 'Sao lưu và Phục hồi',
        '/settings/project-files' => 'Quản lý file mã nguồn',
        '/monitoring/external-checkins' => 'Giám sát thực hành',
        '/monitoring/online-classes' => 'Giám sát Online',
        '/monitoring/evidence' => 'Kho minh chứng',
        '/ai/assistant' => 'Tra cứu thông tin',
        '/tools/api-documentation' => 'Tài liệu API',
        '/tools/announcements' => 'Thông báo nội bộ',
        '/monitoring/document-lookup' => 'Tra cứu văn bản',
        '/discussion' => 'Bảng thảo luận',
        '/messaging' => 'Hộp thư nội bộ',
        '/lecturer-portal' => 'Portal Giảng viên',
    ],

    'permission_aliases' => [
        '/settings/schedules' => '/settings/schedule',
        '/settings/activity-logs' => '/settings/access-log',
        '/monitoring/asset-receptions' => '/monitoring/asset-check',
    ],

    'module_categories' => [
        [
            'title' => 'Tổng quan',
            'modules' => [
                ['id' => '/dashboard', 'label' => 'Bảng điều khiển (Dashboard)', 'icon' => 'layout-dashboard'],
            ],
        ],
        [
            'title' => 'Bộ danh mục',
            'modules' => [
                ['id' => '/personnel/positions', 'label' => 'Danh mục Chức vụ', 'icon' => 'user-circle'],
                ['id' => '/personnel/building-blocks', 'label' => 'Danh mục Dãy nhà', 'icon' => 'building'],
                ['id' => '/personnel/departments', 'label' => 'Danh mục Đơn vị', 'icon' => 'network'],
                ['id' => '/personnel/lecturers', 'label' => 'Danh mục Giảng viên', 'icon' => 'graduation-cap'],
                ['id' => '/personnel/employees', 'label' => 'Danh mục Nhân viên', 'icon' => 'users'],
                ['id' => '/personnel/classrooms', 'label' => 'Danh mục Phòng học', 'icon' => 'school'],
                ['id' => '/personnel/gifts', 'label' => 'Danh mục Quà tặng', 'icon' => 'gift'],
                ['id' => '/personnel/students', 'label' => 'Danh mục Sinh viên', 'icon' => 'users'],
                ['id' => '/personnel/roles', 'label' => 'Danh mục Vai trò', 'icon' => 'shield'],
                ['id' => '/personnel/recognitions', 'label' => 'Việc ghi nhận', 'icon' => 'trophy'],
                ['id' => '/personnel/incident-categories', 'label' => 'Việc phát sinh', 'icon' => 'alert-triangle'],
                ['id' => '/personnel/document-types', 'label' => 'Loại văn bản', 'icon' => 'file-type'],
            ],
        ],
        [
            'title' => 'Công cụ kiểm tra',
            'modules' => [
                ['id' => '/monitoring/homeroom', 'label' => 'Cố vấn học tập', 'icon' => 'user-check'],
                ['id' => '/monitoring/online', 'label' => 'Lớp học online', 'icon' => 'video'],
                ['id' => '/monitoring/in-person', 'label' => 'Lớp học trực tiếp', 'icon' => 'presentation'],
                ['id' => '/monitoring/exams', 'label' => 'Thi kết thúc môn', 'icon' => 'clipboard-list'],
                ['id' => '/monitoring/external-practice', 'label' => 'Thực hành ngoài', 'icon' => 'briefcase'],
                ['id' => '/monitoring/student-violations', 'label' => 'Sinh viên vi phạm', 'icon' => 'user-x'],
                ['id' => '/monitoring/asset-check', 'label' => 'Nhận - Trả tài sản', 'icon' => 'package'],
                ['id' => '/monitoring/requests', 'label' => 'Tiếp nhận yêu cầu', 'icon' => 'file-question'],
                ['id' => '/monitoring/petitions', 'label' => 'Tiếp nhận đơn thư', 'icon' => 'file-text'],
                ['id' => '/monitoring/document-records', 'label' => 'Quản lý hồ sơ', 'icon' => 'file-stack'],
            ],
        ],
        [
            'title' => 'Báo cáo thống kê',
            'modules' => [
                ['id' => '/reports/daily', 'label' => 'Báo cáo cuối ngày', 'icon' => 'calendar-days'],
                ['id' => '/feedback', 'label' => 'Minh chứng ca trực', 'icon' => 'message-quote'],
                ['id' => '/reports/comprehensive', 'label' => 'Thống kê việc KPH', 'icon' => 'bar-chart'],
                ['id' => '/reports/student-violations', 'label' => 'Báo cáo Sinh viên vi phạm', 'icon' => 'user-x'],
                ['id' => '/reports/good-deeds', 'label' => 'Người tốt việc tốt', 'icon' => 'heart'],
                ['id' => '/reports/request-reports', 'label' => 'Báo cáo Tiếp nhận yêu cầu', 'icon' => 'file-stack'],
                ['id' => '/reports/incident-reports', 'label' => 'Báo cáo Tiếp nhận đơn thư', 'icon' => 'alert-circle'],
            ],
        ],
        [
            'title' => 'Thiết lập hệ thống',
            'modules' => [
                ['id' => '/settings/schedule', 'label' => 'Lịch học theo ngày', 'icon' => 'calendar'],
                ['id' => '/settings/parameters', 'label' => 'Tham số hệ thống', 'icon' => 'settings'],
                ['id' => '/settings/permissions', 'label' => 'Phân quyền truy cập', 'icon' => 'key'],
                ['id' => '/settings/access-log', 'label' => 'Nhật ký truy cập', 'icon' => 'history'],
                ['id' => '/settings/backup', 'label' => 'Sao lưu và Phục hồi', 'icon' => 'database'],
                ['id' => '/settings/project-files', 'label' => 'Quản lý file mã nguồn', 'icon' => 'folder-tree'],
            ],
        ],
        [
            'title' => 'Công cụ hỗ trợ',
            'modules' => [
                ['id' => '/monitoring/external-checkins', 'label' => 'Giám sát thực hành', 'icon' => 'qr-code'],
                ['id' => '/monitoring/online-classes', 'label' => 'Giám sát Online', 'icon' => 'monitor-play'],
                ['id' => '/monitoring/evidence', 'label' => 'Kho minh chứng', 'icon' => 'camera'],
                ['id' => '/ai/assistant', 'label' => 'Tra cứu thông tin', 'icon' => 'search'],
                ['id' => '/tools/api-documentation', 'label' => 'Tài liệu API', 'icon' => 'file-text'],
                ['id' => '/tools/announcements', 'label' => 'Thông báo nội bộ', 'icon' => 'megaphone'],
                ['id' => '/monitoring/document-lookup', 'label' => 'Tra cứu văn bản', 'icon' => 'search'],
                ['id' => '/discussion', 'label' => 'Bảng thảo luận', 'icon' => 'messages-square'],
                ['id' => '/messaging', 'label' => 'Hộp thư nội bộ', 'icon' => 'mail'],
                ['id' => '/lecturer-portal', 'label' => 'Portal Giảng viên', 'icon' => 'user-circle'],
            ],
        ],
    ],

    'actions' => [
        'access' => 'Truy cập',
        'view' => 'Xem',
        'add' => 'Thêm',
        'edit' => 'Sửa',
        'delete' => 'Xóa',
        'import' => 'Import',
        'export' => 'Export',
    ],

    'staff_defaults' => [
        '/dashboard' => ['access' => true, 'view' => true],
        '/personnel/positions' => ['access' => true, 'view' => true],
        '/personnel/building-blocks' => ['access' => true, 'view' => true],
        '/personnel/departments' => ['access' => true, 'view' => true],
        '/personnel/lecturers' => ['access' => true, 'view' => true],
        '/personnel/employees' => ['access' => true, 'view' => true],
        '/personnel/classrooms' => ['access' => true, 'view' => true],
        '/personnel/gifts' => ['access' => true, 'view' => true],
        '/personnel/students' => ['access' => true, 'view' => true],
        '/personnel/recognitions' => ['access' => true, 'view' => true],
        '/personnel/incident-categories' => ['access' => true, 'view' => true],
        '/personnel/document-types' => ['access' => true, 'view' => true],
        '/monitoring/homeroom' => ['access' => true, 'view' => true, 'edit' => true],
        '/monitoring/online' => ['access' => true, 'view' => true, 'edit' => true],
        '/monitoring/in-person' => ['access' => true, 'view' => true, 'edit' => true],
        '/monitoring/exams' => ['access' => true, 'view' => true, 'edit' => true],
        '/monitoring/external-practice' => ['access' => true, 'view' => true, 'edit' => true],
        '/monitoring/student-violations' => ['access' => true, 'view' => true, 'edit' => true],
        '/monitoring/asset-check' => ['access' => true, 'view' => true, 'edit' => true],
        '/monitoring/requests' => ['access' => true, 'view' => true, 'edit' => true],
        '/monitoring/petitions' => ['access' => true, 'view' => true, 'edit' => true],
        '/monitoring/document-records' => ['access' => true, 'view' => true, 'add' => true, 'edit' => true],
        '/monitoring/external-checkins' => ['access' => true, 'view' => true, 'add' => true, 'edit' => true],
        '/monitoring/online-classes' => ['access' => true, 'view' => true, 'add' => true, 'edit' => true],
        '/monitoring/document-lookup' => ['access' => true, 'view' => true],
        '/monitoring/evidence' => ['access' => true, 'view' => true, 'add' => true, 'edit' => true, 'delete' => true],
        '/ai/assistant' => ['access' => true, 'view' => true],
        '/tools/api-documentation' => ['access' => true, 'view' => true],
        '/tools/announcements' => ['access' => true, 'view' => true, 'add' => true, 'edit' => true, 'delete' => true],
        '/discussion' => ['access' => true, 'view' => true, 'add' => true, 'edit' => true],
        '/messaging' => ['access' => true, 'view' => true, 'add' => true, 'edit' => true],
        '/lecturer-portal' => ['access' => true, 'view' => true, 'add' => true, 'edit' => true],
        '/reports/daily' => ['access' => true, 'view' => true],
        '/feedback' => ['access' => true, 'view' => true, 'add' => true, 'edit' => true],
        '/reports/comprehensive' => ['access' => true, 'view' => true],
        '/reports/student-violations' => ['access' => true, 'view' => true],
        '/reports/good-deeds' => ['access' => true, 'view' => true],
        '/reports/request-reports' => ['access' => true, 'view' => true],
        '/reports/incident-reports' => ['access' => true, 'view' => true],
    ],

    'page_heading_icons' => [
        '_default' => ['icon' => 'layout', 'tone' => 'primary'],
        'Tổng quan' => ['icon' => 'layout', 'tone' => 'sky'],
        'Thiết lập hệ thống' => ['icon' => 'settings', 'tone' => 'gray'],
        'Công cụ hỗ trợ' => ['icon' => 'sparkles', 'tone' => 'purple'],
        'Báo cáo thống kê' => ['icon' => 'bar-chart', 'tone' => 'indigo'],
        'Chức vụ' => ['icon' => 'user-circle', 'tone' => 'indigo'],
        'Dãy nhà' => ['icon' => 'building', 'tone' => 'amber'],
        'Đơn vị' => ['icon' => 'landmark', 'tone' => 'rose'],
        'Giảng viên' => ['icon' => 'graduation', 'tone' => 'cyan'],
        'Nhân viên' => ['icon' => 'users', 'tone' => 'fuchsia'],
        'Phòng học' => ['icon' => 'door', 'tone' => 'yellow'],
        'Quà tặng' => ['icon' => 'gift', 'tone' => 'pink'],
        'Sinh viên' => ['icon' => 'users', 'tone' => 'lime'],
        'Vai trò' => ['icon' => 'shield', 'tone' => 'purple'],
        'Việc ghi nhận' => ['icon' => 'note', 'tone' => 'teal'],
        'Việc phát sinh' => ['icon' => 'folder', 'tone' => 'pink'],
        'Loại văn bản' => ['icon' => 'file-text', 'tone' => 'blue'],
        'Cố vấn học tập' => ['icon' => 'book-user', 'tone' => 'lime'],
        'Lớp học online' => ['icon' => 'monitor', 'tone' => 'blue'],
        'Lớp học trực tiếp' => ['icon' => 'monitor', 'tone' => 'green'],
        'Thi kết thúc môn' => ['icon' => 'file-text', 'tone' => 'purple'],
        'Thực hành ngoài' => ['icon' => 'activity', 'tone' => 'orange'],
        'Vi phạm sinh viên' => ['icon' => 'ban', 'tone' => 'rose'],
        'Sinh viên vi phạm' => ['icon' => 'ban', 'tone' => 'rose'],
        'Nhận - Trả tài sản' => ['icon' => 'folder', 'tone' => 'pink'],
        'Tiếp nhận yêu cầu' => ['icon' => 'mail', 'tone' => 'teal'],
        'Tiếp nhận đơn thư' => ['icon' => 'user-circle', 'tone' => 'rose'],
        'Quản lý hồ sơ văn bản' => ['icon' => 'folder', 'tone' => 'amber'],
        'Quản lý hồ sơ' => ['icon' => 'folder', 'tone' => 'amber'],
        'Giám sát thực hành' => ['icon' => 'map-pin', 'tone' => 'blue'],
        'Giám sát Online' => ['icon' => 'monitor', 'tone' => 'purple'],
        'Minh chứng ca trực' => ['icon' => 'check', 'tone' => 'amber'],
        'Kho minh chứng' => ['icon' => 'camera', 'tone' => 'blue'],
        'Quản lý Minh chứng' => ['icon' => 'camera', 'tone' => 'blue'],
        'Tra cứu văn bản' => ['icon' => 'search', 'tone' => 'sky'],
        'Tra cứu thông tin' => ['icon' => 'search', 'tone' => 'blue'],
        'Tài liệu API' => ['icon' => 'file-text', 'tone' => 'cyan'],
        'Thông báo nội bộ' => ['icon' => 'megaphone', 'tone' => 'amber'],
        'Trợ lý Tra cứu' => ['icon' => 'search', 'tone' => 'blue'],
        'Bảng thảo luận' => ['icon' => 'layout', 'tone' => 'pink'],
        'Hộp thư nội bộ' => ['icon' => 'mail', 'tone' => 'teal'],
        'Hộp thư' => ['icon' => 'mail', 'tone' => 'teal'],
        'Portal Giảng viên' => ['icon' => 'user-circle', 'tone' => 'indigo'],
        'Lịch học theo ngày' => ['icon' => 'calendar', 'tone' => 'pink'],
        'Tham số hệ thống' => ['icon' => 'settings', 'tone' => 'lime'],
        'Cài đặt hệ thống' => ['icon' => 'settings', 'tone' => 'gray'],
        'Phân quyền truy cập' => ['icon' => 'key', 'tone' => 'orange'],
        'Phân quyền:' => ['icon' => 'key', 'tone' => 'orange'],
        'Ghi nhận:' => ['icon' => 'activity', 'tone' => 'green'],
        'Thêm ' => ['icon' => 'add', 'tone' => 'green'],
        'Sửa ' => ['icon' => 'edit', 'tone' => 'amber'],
        'Nhật ký truy cập' => ['icon' => 'history', 'tone' => 'cyan'],
        'Sao lưu và Phục hồi' => ['icon' => 'database', 'tone' => 'indigo'],
        'Sao lưu dữ liệu' => ['icon' => 'database', 'tone' => 'indigo'],
        'Quản lý file mã nguồn' => ['icon' => 'folder-tree', 'tone' => 'violet'],
        'Hồ sơ nhân viên' => ['icon' => 'user-cog', 'tone' => 'primary'],
        'Báo cáo cuối ngày' => ['icon' => 'file-text', 'tone' => 'sky'],
        'Thống kê việc KPH' => ['icon' => 'bar-chart', 'tone' => 'indigo'],
        'Báo cáo Sinh viên vi phạm' => ['icon' => 'ban', 'tone' => 'rose'],
        'Người tốt việc tốt' => ['icon' => 'heart', 'tone' => 'green'],
        'Báo cáo Tiếp nhận yêu cầu' => ['icon' => 'mail', 'tone' => 'teal'],
        'Báo cáo Tiếp nhận đơn thư' => ['icon' => 'user-circle', 'tone' => 'rose'],
    ],

    'catalog_entity_icons' => [
        'positions' => ['icon' => 'user-circle', 'tone' => 'indigo'],
        'building-blocks' => ['icon' => 'building', 'tone' => 'amber'],
        'departments' => ['icon' => 'landmark', 'tone' => 'rose'],
        'classrooms' => ['icon' => 'door', 'tone' => 'yellow'],
        'lecturers' => ['icon' => 'graduation', 'tone' => 'cyan'],
        'employees' => ['icon' => 'users', 'tone' => 'fuchsia'],
        'students' => ['icon' => 'users', 'tone' => 'lime'],
        'gifts' => ['icon' => 'gift', 'tone' => 'pink'],
        'roles' => ['icon' => 'shield', 'tone' => 'purple'],
        'recognitions' => ['icon' => 'note', 'tone' => 'teal'],
        'incident-categories' => ['icon' => 'folder', 'tone' => 'pink'],
        'document-types' => ['icon' => 'file-text', 'tone' => 'blue'],
        'student-violations' => ['icon' => 'ban', 'tone' => 'rose'],
        'requests' => ['icon' => 'mail', 'tone' => 'teal'],
        'petitions' => ['icon' => 'user-circle', 'tone' => 'rose'],
        'asset-receptions' => ['icon' => 'folder', 'tone' => 'pink'],
        'document-records' => ['icon' => 'folder', 'tone' => 'amber'],
        'announcements' => ['icon' => 'megaphone', 'tone' => 'amber'],
    ],

    'project_files' => [
        'root' => env('NTTU_PROJECT_ROOT', base_path()),
        'blocked_dir_names' => ['vendor', 'node_modules', '.git'],
        'blocked_path_prefixes' => [
            'storage/framework',
            'storage/logs',
            'bootstrap/cache',
        ],
        'max_edit_kb' => 512,
        'max_upload_mb' => (int) env('NTTU_PROJECT_MAX_UPLOAD_MB', 50),
    ],

    'firebase' => [
        'api_key' => env('FIREBASE_API_KEY', 'AIzaSyBXjBBAnT-qIchTelWU6YWAvzXmkEgMBBw'),
        'auth_domain' => env('FIREBASE_AUTH_DOMAIN', 'kiemtranoibo-ccks.firebaseapp.com'),
        'project_id' => env('FIREBASE_PROJECT_ID', 'kiemtranoibo-ccks'),
        'email' => env('FIREBASE_EMAIL'),
        'password' => env('FIREBASE_PASSWORD'),
    ],

    'lecturer_portal' => [
        /** Miền email Google được phép (phân tách bằng dấu phẩy). Email có trong bảng lecturers luôn được chấp nhận. */
        'email_domains' => env('LECTURER_PORTAL_EMAIL_DOMAINS', 'nttu.edu.vn,ntt.edu.vn,gmail.com'),
    ],

    /**
     * Kênh công khai — độc lập (không đăng nhập app nội bộ), dữ liệu đổ về Giám sát.
     *
     * | Kênh              | Xác thực        | Bảng / API              | Trang giám sát nội bộ        |
     * |-------------------|-----------------|-------------------------|------------------------------|
     * | lecturer-portal   | Google browser  | external_checkins       | Giám sát thực hành           |
     * | ex-online         | API key (ext)   | online_checkins + schedules | Giám sát Online          |
     * | discussion        | Token / guest   | discussion_sections     | (hỗ trợ lớp, không check-in) |
     */
    'public_channels' => [
        'lecturer_portal' => [
            'path' => '/lecturer-portal',
            'auth' => 'google',
            'model' => 'external_checkins',
            'monitoring_route' => 'external-checkins.index',
            'monitoring_label' => 'Giám sát thực hành',
        ],
        'ex_online' => [
            'path' => null,
            'auth' => 'api_key',
            'model' => 'online_checkins',
            'monitoring_route' => 'online-classes.index',
            'monitoring_label' => 'Giám sát Online',
        ],
        'discussion' => [
            'path' => '/discussion',
            'auth' => 'moderator_token_or_guest',
            'model' => 'discussion_sections',
            'monitoring_route' => null,
            'monitoring_label' => null,
        ],
    ],

    /** Google Sheet báo cáo tổng hợp học kỳ (Người tốt việc tốt, Tiếp nhận yêu cầu, …). */
    'summary_report_google_sheet_id' => env(
        'SUMMARY_REPORT_GOOGLE_SHEET_ID',
        '18eUrHg297CBKNRkpIqLzQICatmmDeGNK-D16minE7Uo',
    ),

    /** Minh chứng ca trực — Google Sheet lưu dòng báo cáo. */
    'feedback_google_sheet_id' => env(
        'FEEDBACK_GOOGLE_SHEET_ID',
        '1lneRw5i8mq651ezFpjIquKevK-aR6J4WPRgMCPo2vNA',
    ),

    /** Minh chứng ca trực — thư mục Drive lưu file đính kèm. */
    'feedback_google_drive_folder_id' => env(
        'FEEDBACK_GOOGLE_DRIVE_FOLDER_ID',
        '1Xjw3fA-iu4ipVWv-GhrOBq5F8YlQ42iG',
    ),
];
